
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.5.0
  creationTimestamp: null
  name: algorithms.catalog.modeld.io
spec:
  group: catalog.modeld.io
  names:
    categories:
    - catalog
    - modeld
    - all
    kind: Algorithm
    listKind: AlgorithmList
    plural: algorithms
    singular: algorithm
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: ML Framework name
      jsonPath: .spec.frameworkName
      name: Framework
      type: string
    - jsonPath: .spec.url
      name: Repository
      type: string
    - description: ML task name
      jsonPath: .spec.task
      name: Task
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Algorithm define the metadata about a machine learning algorithm.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: AlgorithmSpec describes the attributes of an machine learning
              algorithm
            properties:
              categoricalParameters:
                description: CategoricalParameters is the list of categorical hyper
                  parameters ranges
                items:
                  description: CategoricalParameter contain the specification of an
                    categorical hyper parameter
                  properties:
                    defaultValue:
                      description: DefaultValue if the default categorical value
                      type: string
                    enums:
                      description: Enums defines the list of values
                      items:
                        type: string
                      type: array
                    name:
                      description: Name is the name of the hyper parameter
                      type: string
                  type: object
                type: array
              description:
                default: ""
                description: Description is the description of the algorithm
                type: string
              floatParameters:
                description: FloatParameters is the list of float hyper parameters
                  ranges
                items:
                  description: FloatParameter contain the specification of an float
                    hyper parameter
                  properties:
                    defaultValue:
                      description: Default float value
                      type: number
                    log:
                      description: Log specify if this hyper paramer is logartimic
                      type: boolean
                    max:
                      description: Max is the maximum value
                      type: number
                    min:
                      description: Min is the minimum value
                      type: number
                    name:
                      description: Name is the name of the hyper parameter
                      type: string
                  type: object
                type: array
              frameworkName:
                description: FrameworkName is a reference to library
                type: string
              integerParameters:
                description: IntegerParameters is the list of integer hyper parameter
                  ranges.
                items:
                  description: IntParameter contain the specification of an integer
                    hyper parameter
                  properties:
                    defaultValue:
                      description: DefaultValue is the default value of the parameter
                      format: int32
                      type: integer
                    max:
                      description: Max is the maximum value of the hyper parameter
                        range
                      format: int32
                      type: integer
                    min:
                      description: Min is the minimum value of the hyper parameter
                        range
                      format: int32
                      type: integer
                    name:
                      description: Name is the name of the hyper parameter
                      type: string
                    type:
                      description: Type is the datatype of the parameter
                      enum:
                      - numeric
                      - numeric-list
                      - categorical
                      - categorical-list
                      - datetime
                      - string
                      - string-list
                      - url
                      - path
                      - file
                      - useless
                      - image
                      - video
                      - audio
                      - boolean
                      - json
                      type: string
                  type: object
                type: array
              sparse:
                default: false
                description: Sparse indicate if this algorithm can deal with sparse
                  data
                type: boolean
              task:
                description: Task is the machine learning task (binary classification
                  / regression)
                enum:
                - binary-classification
                - multi-classification
                - multi-label-classification
                - text-classification
                - regression
                - forecasting
                - clustering
                - recommendation
                - outlier-detection
                - novelty-detection
                - topic-modeling
                - auto
                - unknown
                type: string
              url:
                default: ""
                description: URL is a url to the html page describing the algorithm
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
