
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.5.0
  creationTimestamp: null
  name: datasets.data.modeld.io
spec:
  group: data.modeld.io
  names:
    categories:
    - data
    - modeld
    - all
    kind: Dataset
    listKind: DatasetList
    plural: datasets
    shortNames:
    - ds
    singular: dataset
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: string
    - jsonPath: .spec.versionName
      name: Version
      type: string
    - jsonPath: .spec.datasourceName
      name: Location Origin
      type: string
    - jsonPath: .status.phase
      name: Status
      type: string
    - jsonPath: .status.statistics.rows
      name: Rows
      type: integer
    - jsonPath: .status.statistics.cols
      name: Columns
      type: integer
    - jsonPath: .status.statistics.fileSize
      name: Size
      type: integer
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Dataset represents a single batch of data
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: DatasetSpec defines the desired state of a dataset
            properties:
              datasourceName:
                description: DataSourceName is the name of the data source which created
                  this dataset. For example flat file
                maxLength: 63
                minLength: 1
                type: string
              description:
                description: User provided description
                maxLength: 512
                type: string
              labeled:
                description: Labeled indicates if this dataset is labeled or not.
                  kubebuilder:default:=true
                type: boolean
              location:
                description: Folder of the actual data resides.
                properties:
                  bucketName:
                    type: string
                  path:
                    description: Path to the full data file (e.g. csv file).
                    type: string
                required:
                - bucketName
                - path
                type: object
              origin:
                description: Define the data location. The operator will copy the
                  data from this location into the live location. The datafiles are
                  initially uploaded to this location.
                properties:
                  bucketName:
                    type: string
                  path:
                    description: Path to the full data file (e.g. csv file).
                    type: string
                required:
                - bucketName
                - path
                type: object
              owner:
                description: The account name of the owner of this dataset
                type: string
              report:
                description: If true, a dataset report should be generated for this
                  dataset. kubebuilder:default:=true
                type: boolean
              validate:
                description: If true, we should validate the dataset kubebuilder:default:=true
                type: boolean
              versionName:
                description: VersionName is the data product version of the dataset
                  required.
                maxLength: 63
                type: string
            type: object
          status:
            description: DatasetStatus defines the observed state of Dataset
            properties:
              conditions:
                description: Represents the latest available observations of a dataset
                  state.
                items:
                  description: DatasetCondition describes the state of a dataset at
                    a certain point.
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition.
                      type: string
                    reason:
                      description: The reason for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, AutoScaler.
                      type: string
                    type:
                      description: Condition on the dataset
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              imbalanced:
                description: Based on the actual data, treat this dataset as imbalanced.
                type: boolean
              phase:
                description: The phase of the dataset processing
                type: string
              profileUri:
                description: A reference to the visualization uri which were produce
                  during processing
                type: string
              reportName:
                description: Reference to the report object that was generated for
                  the dataset
                type: string
              sigs:
                description: Sha256 sig of the files
                properties:
                  data:
                    description: Data to the full data file (e.g. csv file).
                    type: string
                  labels:
                    description: The location of the labels file (If exist)
                    type: string
                  test:
                    description: the location of the training data, if different from
                      the data.
                    type: string
                  train:
                    description: path to the training set
                    type: string
                  validation:
                    description: Pointer to the validation
                    type: string
                required:
                - data
                - train
                type: object
              statistics:
                description: Statistics for the dataset. The statistics contain information
                  about each column.
                properties:
                  cols:
                    description: number of columns, used mainly to show the columns
                      in the kubectl
                    format: int32
                    type: integer
                  columns:
                    description: Columns contain the collection of statistics for
                      each attribute
                    items:
                      description: Hold the statistical parameters about a single
                        attribute
                      properties:
                        distinc:
                          format: int32
                          type: integer
                        highCorr:
                          description: This column has high corrolation with another
                            feature and should be dropped. The value is set during
                            the profile process.
                          type: boolean
                        highCred:
                          description: This column has high cardinality and should
                            be ignored. The value is set during the profile process.
                          type: boolean
                        ignored:
                          description: Should this column be ignored, as specified
                            by the user. This value is derived from the schema
                          type: boolean
                        importance:
                          description: The feature importance
                          type: number
                        invalid:
                          description: The number of invalid values
                          format: int32
                          type: integer
                        kurtosis:
                          description: Kurtosis is the standard deviation value of
                            the attribute
                          type: number
                        max:
                          description: Max is the maximum value of the attribute
                          type: number
                        mean:
                          description: Mean is the mean value of the attribute
                          type: number
                        min:
                          description: Min is the minimum value of the attribute
                          type: number
                        missing:
                          description: The number of missing values
                          format: int32
                          type: integer
                        name:
                          description: FileName is the name of the column
                          type: string
                        nullable:
                          description: Is this column is nullable. This value is derived
                            from the schema.
                          type: boolean
                        p25:
                          description: Pct25 is the 25 precent point
                          type: number
                        p50:
                          description: Pct50 is the median
                          type: number
                        p75:
                          description: Pct75 is the 75% point
                          type: number
                        skew:
                          description: Mark that this column is skewed and would require
                            a power transform If skewness is less than -1 or greater
                            than 1, the distribution is highly skewed. If skewness
                            is between -1 and -0.5 or between 0.5 and 1, the distribution
                            is moderately skewed. If skewness is between -0.5 and
                            0.5, the distribution is approximately symmetric
                          type: boolean
                        skewness:
                          description: Skewness is the standard deviation value of
                            the attribute
                          type: number
                        stddev:
                          description: StdDev is the standard deviation value of the
                            attribute
                          type: number
                        target:
                          description: Is this the target attribute, the value is
                            derived from the schema
                          type: boolean
                        zeros:
                          description: Zeros is the numbers of zeros in the feature
                          type: number
                      type: object
                    type: array
                  fileSize:
                    description: file size in bytes
                    format: int32
                    type: integer
                  rows:
                    description: number of rows in the dataset
                    format: int32
                    type: integer
                type: object
            type: object
        required:
        - metadata
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
