
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.5.0
  creationTimestamp: null
  name: modelpipelineruns.training.modeld.io
spec:
  group: training.modeld.io
  names:
    categories:
    - train
    - modeld
    - all
    kind: ModelPipelineRun
    listKind: ModelPipelineRunList
    plural: modelpipelineruns
    shortNames:
    - pr
    singular: modelpipelinerun
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: string
    - jsonPath: .status.phase
      name: Status
      type: string
    - jsonPath: .status.pipelineName
      name: ModelPipeline
      type: string
    - jsonPath: .status.versionName
      name: Version
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ModelPipelineRun represent a execution of a pipeline
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ModelPipelineRunSpec is the desired state of the ModelPipelineRun
              resource
            properties:
              description:
                default: ""
                description: User provided description
                type: string
              owner:
                default: ""
                description: The owner account name
                type: string
              pipelineName:
                default: ""
                description: PipelineName is the name of the pipeline specification
                  for this pipeline
                type: string
              triggerName:
                default: ""
                description: TriggerName denote the trigger that fired this pipeline
                  run
                type: string
              versionName:
                default: ""
                description: User provided description
                type: string
            type: object
          status:
            description: ModelPipelineRunStatus is the observed state of the ModelPipelineRun
              resource .
            properties:
              acceptanceStage:
                description: Staging is status for each qa stage.
                properties:
                  approved:
                    description: Approved indicates that the stage is approved.
                    type: boolean
                  approvedAt:
                    description: ApprovedAt indicates the time of approval
                    format: date-time
                    type: string
                  approvedBy:
                    description: ApprovedBy indicates the account that approve this
                      model.
                    type: string
                  endTime:
                    description: End time is the end time of the stage.
                    format: date-time
                    type: string
                  error:
                    description: Error record the error if occurred
                    type: string
                  phase:
                    description: Phase is the phase of the stage
                    type: string
                  score:
                    description: Score is the score of
                    type: number
                  startTime:
                    description: Start time is the start time of the stage
                    format: date-time
                    type: string
                type: object
              capacityStage:
                description: ReleaseStage is the status for the production stage.
                properties:
                  approved:
                    description: Approved indicates that the stage is approved.
                    type: boolean
                  approvedAt:
                    description: ApprovedAt indicates the time of approval
                    format: date-time
                    type: string
                  approvedBy:
                    description: ApprovedBy indicates the account that approve this
                      model.
                    type: string
                  endTime:
                    description: End time is the end time of the stage.
                    format: date-time
                    type: string
                  error:
                    description: Error record the error if occurred
                    type: string
                  phase:
                    description: Phase is the phase of the stage
                    type: string
                  score:
                    description: Score is the score of
                    type: number
                  startTime:
                    description: Start time is the start time of the stage
                    format: date-time
                    type: string
                type: object
              completionTime:
                format: date-time
                type: string
              conditions:
                items:
                  description: ModelPipelineRunCondition describes the state of a
                    ModelPipelineRun at a certain point.
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition.
                      type: string
                    reason:
                      description: The reason for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of  condition.
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              dataStage:
                description: data is the status for the data stage.
                properties:
                  approved:
                    description: Approved indicates that the stage is approved.
                    type: boolean
                  approvedAt:
                    description: ApprovedAt indicates the time of approval
                    format: date-time
                    type: string
                  approvedBy:
                    description: ApprovedBy indicates the account that approve this
                      model.
                    type: string
                  endTime:
                    description: End time is the end time of the stage.
                    format: date-time
                    type: string
                  error:
                    description: Error record the error if occurred
                    type: string
                  phase:
                    description: Phase is the phase of the stage
                    type: string
                  score:
                    description: Score is the score of
                    type: number
                  startTime:
                    description: Start time is the start time of the stage
                    format: date-time
                    type: string
                type: object
              folder:
                description: Folder for pipeline run artifacts. This is assigned by
                  the system The folder contains all the pipeline artifacts - metadata,
                  logs
                type: string
              phase:
                description: The phase of the pipeline run
                type: string
              prodStage:
                description: ReleaseStage is the status for the production stage.
                properties:
                  approved:
                    description: Approved indicates that the stage is approved.
                    type: boolean
                  approvedAt:
                    description: ApprovedAt indicates the time of approval
                    format: date-time
                    type: string
                  approvedBy:
                    description: ApprovedBy indicates the account that approve this
                      model.
                    type: string
                  endTime:
                    description: End time is the end time of the stage.
                    format: date-time
                    type: string
                  error:
                    description: Error record the error if occurred
                    type: string
                  phase:
                    description: Phase is the phase of the stage
                    type: string
                  score:
                    description: Score is the score of
                    type: number
                  startTime:
                    description: Start time is the start time of the stage
                    format: date-time
                    type: string
                type: object
              startTime:
                format: date-time
                type: string
              studyName:
                type: string
              trainingStage:
                description: dev is the status for the dev stage.
                properties:
                  approved:
                    description: Approved indicates that the stage is approved.
                    type: boolean
                  approvedAt:
                    description: ApprovedAt indicates the time of approval
                    format: date-time
                    type: string
                  approvedBy:
                    description: ApprovedBy indicates the account that approve this
                      model.
                    type: string
                  endTime:
                    description: End time is the end time of the stage.
                    format: date-time
                    type: string
                  error:
                    description: Error record the error if occurred
                    type: string
                  phase:
                    description: Phase is the phase of the stage
                    type: string
                  score:
                    description: Score is the score of
                    type: number
                  startTime:
                    description: Start time is the start time of the stage
                    format: date-time
                    type: string
                type: object
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
