apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- catalog.modela.ai_algorithms.yaml
- catalog.modela.ai_clouds.yaml
- catalog.modela.ai_managedimages.yaml
- catalog.modela.ai_mlframeworks.yaml
- catalog.modela.ai_pretrainedmodels.yaml
- catalog.modela.ai_publicdatasets.yaml
- catalog.modela.ai_workloadclasses.yaml
- data.modela.ai_datapipelineruns.yaml
- data.modela.ai_datapipelines.yaml
- data.modela.ai_dataproducts.yaml
- data.modela.ai_dataproductversions.yaml
- data.modela.ai_datasets.yaml
- data.modela.ai_datasources.yaml
- data.modela.ai_entities.yaml
- data.modela.ai_featuregroups.yaml
- data.modela.ai_featurehistograms.yaml
- data.modela.ai_reciperuns.yaml
- data.modela.ai_recipes.yaml
- data.modela.ai_sqlqueries.yaml
- data.modela.ai_sqlqueryruns.yaml
- data.modela.ai_webrequestruns.yaml
- data.modela.ai_webrequests.yaml
- inference.modela.ai_cronpredictions.yaml
- inference.modela.ai_dataapps.yaml
- inference.modela.ai_predictions.yaml
- inference.modela.ai_predictors.yaml
- infra.modela.ai_accounts.yaml
- infra.modela.ai_alerts.yaml
- infra.modela.ai_apitokens.yaml
- infra.modela.ai_attachments.yaml
- infra.modela.ai_commits.yaml
- infra.modela.ai_connections.yaml
- infra.modela.ai_labs.yaml
- infra.modela.ai_licenses.yaml
- infra.modela.ai_modelasystems.yaml
- infra.modela.ai_notifiers.yaml
- infra.modela.ai_servingsites.yaml
- infra.modela.ai_tenants.yaml
- infra.modela.ai_userroleclasses.yaml
- infra.modela.ai_virtualbuckets.yaml
- infra.modela.ai_virtualclusters.yaml
- infra.modela.ai_virtualvolumes.yaml
- team.modela.ai_meetings.yaml
- team.modela.ai_postmortems.yaml
- team.modela.ai_reviews.yaml
- team.modela.ai_runbooks.yaml
- team.modela.ai_todos.yaml
- training.modela.ai_modelautobuilders.yaml
- training.modela.ai_modelclasses.yaml
- training.modela.ai_modelpipelineruns.yaml
- training.modela.ai_modelpipelines.yaml
- training.modela.ai_models.yaml
- training.modela.ai_notebookruns.yaml
- training.modela.ai_notebooks.yaml
- training.modela.ai_reports.yaml
- training.modela.ai_studies.yaml
